SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
STARTING_SCORE = 0

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_ACCELERATION = 200
PLAYER_MAX_SPEED = 300
PLAYER_LIVES = 3
BONUS_PLAYER_LIFE_SCORE = 10000

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_KILL_SCORE = 100
SMALL_ASTEROID_SCORE = 500


SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.2
PLAYER_SHOT_COOLDOWN_DEFAULT = PLAYER_SHOT_COOLDOWN
RAPID_FIRE_COOLDOWN = 0.1
POWERUP_DURATION = 10.0
SPREAD_BULLETS = 5
SPREAD_ANGLE_DEG = 15
POWER_UP_DROP_CHANCE = 0.33
POWERUP_RADIUS = 15 

SCORE_FONT_SIZE = 24